# fly.toml app configuration file generated for whispershard-agent-poc on 2025-05-07T20:41:59-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whispershard-agent-poc'
primary_region = 'ord'

[experimental]
  auto_rollback = true

[env]
  PORT = '3000'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
