name: Deploy to Fly.io

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions@1.4
        with:
          apiToken: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --remote-only
